# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ""
description: ""
keywords:
author: Zehui
language: en
timezone: ""

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://ahui9605.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: "git"
  repository: https://github.com/ahui9605/ahui9605.github.io.git
  branch: main

social:
  fab fa-github: https://github.com/ahui9605 || Github
  fas fa-envelope: mailto:zehui.liu@gallaudet.edu || Email
  fa-brands fa-twitter: https://twitter.com

avatar:
  img: /images/Logo/blog_avatar.png
  effect: false # 头像会一直转圈

#右上角菜单设置
menu:
  Home: / ||
  Category: /categories/ ||
  Link: /link/ ||

# 主页图片
# index_img: https://file.moyublog.com/d/file/2020-11-17/7523db714dc7fbc67bdd580e42f8c9e2.jpg

# 是否禁用置顶图
disable_top_img: true

index_post_content:
  method: 2
  length: 500 # if you set method to 2 or 3, the length need to config

#互动性特效，页面背景可点击互动
canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: true #设置是否每次点击都更换綵带
  mobile: true # false 手机端不显示 true 手机端显示

# 图片大图查看模式
fancybox: true

# 开启图片Figcaption描述文字显示
# 优先显示图片的 title 属性，然后是 alt 属性
photofigcaption: true

# 在文章页，会有一个目录，用于显示TOC。
toc:
  post: true
  page: true
  number: false
  expand: true
  style_simple: true # for post

#尾页
footer:
  owner:
    enable: true
    since: 2022
  custom_text: Hi, welcome to my <a href="#">blog</a>!

# A simple 404 page
error_404:
  enable: true
  subtitle: "page not found, please try again"
  background: "https://img.freepik.com/free-vector/oops-404-error-with-broken-robot-concept-illustration_114360-1932.jpg?w=2000"

#版权
post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

#文章结尾下一章/上一章设置关闭
post_pagination: false

# 鼠标悬停超过65秒提前预判预加载 # https://instant.page/ # prefetch (预加载)
instantpage: true

# 当用户点击链接，通过ajax更新页面需要变化的部分，然后使用HTML5的pushState修改浏览器的URL地址。
# 这样可以不用重复加载相同的资源（css/js）， 从而提升网页的加载速度。
# Pjax [Beta]
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax:
  enable: true
  exclude:
    # - /music/
    # - /no-pjax/

#相关post推荐关闭
related_post:
  enable: false
  limit: 6 # 显示推荐文章数目
  date_type: created # or created or updated 文章日期显示创建日或者更新日

#侧边栏设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手机页面（ 显示宽度 < 768px ）是否显示aside内容
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: Welcome to my personal blog!
    button:
      enable: false
  card_announcement:
    enable: false
    content: -none
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true #标签颜色种类为true
  card_archives:
    enable: false
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: false
    post_count: true
    last_push_date: true

#搜索功能 和config.yml的搜索一起使用
local_search:
  enable: true
  preload: true

#代码背景颜色
highlight_theme: pale night

#代码换行
code_word_wrap: true
#将来可以考虑增加编程语言制作的flowchart流程图
# mermaid
# see https://github.com/mermaid-js/mermaid
# mermaid:
#   enable: true
#   # built-in themes: default/forest/dark/neutral
#   theme:
#     light: default
#     dark: dark

#网页缓存
# pwa:
#   enable: true
#   manifest: /img/pwa/manifest.json
#   apple_touch_icon: /img/pwa/apple-touch-icon.png
#   favicon_32_32: /img/pwa/32.png
#   favicon_16_16: /img/pwa/16.png
#   mask_icon: /img/pwa/safari-pinned-tab.svg

# 标签外挂：
note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: simple
  icons: false
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0
